version: "3"
services:
  uaa:
    image: go-uaa:latest
    container_name: "go-uaa"
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEVELOPMENT: "true"
    ports:
      - 8888:8888
      - 9273:9273
    depends_on:
      - postgres
      - rabbitmq
    restart: on-failure
    volumes:
      - .:/app

  swagger:
    image: swaggerapi/swagger-ui:v4.12.0
    ports:
      - 8887:8080
    environment:
      SWAGGER_JSON_URL: http://localhost:8888/openapi.yaml
      BASE_URL: /swagger

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: uaa
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://test_user:test_password@postgres:5432/uaa?sslmode=disable"
    depends_on:
      - postgres
      - prometheus

  
  rabbitmq:
    image: rabbitmq:3.8.19-management
    environment:
      RABBITMQ_DEFAULT_USER: test_user
      RABBITMQ_DEFAULT_PASS: test_password
      RABBITMQ_DEFAULT_VHOST: uaa
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 15674:15674
      - 25672:25672

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./tools/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
     - 3000:3000

  kibana:
    image: kibana:7.6.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  apm-server:
    image: store/elastic/apm-server:7.6.0
    ports:
      - "8200:8200"
    environment:
      output.elasticsearch.hosts: 'http://elasticsearch:9200'
      apm-server.host: "0.0.0.0:8200"
      apm-server.secret_token: "xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
      setup.kibana.host: "kibana:5601"
      setup.template.enabled: "true"
      logging.to_files: "false"
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.6.0
    command: logstash -f /usr/local/etc/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./tools/logstash.conf:/usr/local/etc/logstash.conf

volumes:
  db:
  elasticsearch_data:
