version: "3"
services:
  iam:
    image: go-iam:latest
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEVELOPMENT: "true"
    ports:
      - 8888:8888
    depends_on:
      - iam-postgres
      - rabbitmq
    restart: on-failure
    volumes:
      - .:/app

  swagger:
    image: swaggerapi/swagger-ui:v4.12.0
    ports:
      - 8887:8080
    environment:
      SWAGGER_JSON_URL: http://localhost:8888/openapi.yaml
      BASE_URL: /swagger

  iam-postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: iam
    ports:
      - 5432:5432
    volumes:
      - iam_db:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3.8.19-management
    environment:
      RABBITMQ_DEFAULT_USER: test_user
      RABBITMQ_DEFAULT_PASS: test_password
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 15674:15674
      - 25672:25672

  kibana:
    image: kibana:7.6.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  apm-server:
    image: elastic/apm-server:7.6.0
    ports:
      - "8200:8200"
    environment:
      output.elasticsearch.hosts: 'http://elasticsearch:9200'
      apm-server.host: "0.0.0.0:8200"
      apm-server.secret_token: "xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
      setup.kibana.host: "kibana:5601"
      setup.template.enabled: "true"
      logging.to_files: "false"
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.6.0
    command: logstash -f /usr/local/etc/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./tools/logstash.conf:/usr/local/etc/logstash.conf

volumes:
  iam_db:
  elasticsearch_data:
