apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: iam-web-server
  name: iam-web-server
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app.kubernetes.io/name: iam-web-server
status:
  loadBalancer: {}
