// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	permission "go-uaa/src/domain/permission"

	mock "github.com/stretchr/testify/mock"
)

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

// FindByNames provides a mock function with given fields: ctx, permissionNames
func (_m *PermissionRepository) FindByNames(ctx context.Context, permissionNames []string) ([]permission.Permission, error) {
	ret := _m.Called(ctx, permissionNames)

	var r0 []permission.Permission
	if rf, ok := ret.Get(0).(func(context.Context, []string) []permission.Permission); ok {
		r0 = rf(ctx, permissionNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, permissionNames)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *PermissionRepository) Save(ctx context.Context, _a1 permission.Permission) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, permission.Permission) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPermissionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPermissionRepository(t mockConstructorTestingTNewPermissionRepository) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
