// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ThirdPartyAuthURLBuilder is an autogenerated mock type for the ThirdPartyAuthURLBuilder type
type ThirdPartyAuthURLBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields: callbackURL
func (_m *ThirdPartyAuthURLBuilder) Build(callbackURL string) string {
	ret := _m.Called(callbackURL)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(callbackURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewThirdPartyAuthURLBuilder interface {
	mock.TestingT
	Cleanup(func())
}

// NewThirdPartyAuthURLBuilder creates a new instance of ThirdPartyAuthURLBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewThirdPartyAuthURLBuilder(t mockConstructorTestingTNewThirdPartyAuthURLBuilder) *ThirdPartyAuthURLBuilder {
	mock := &ThirdPartyAuthURLBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
