name: IAM CI Workflow
on:
  push:
permissions:
  contents: read
jobs:
  iam-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        run: make setup-env
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test
      - name: Build docker image
        run: docker build -t djrevok/go-iam:latest .
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish docker image
        if: github.ref == 'refs/heads/develop'
        uses: actions-hub/docker@master
        with:
          args: push djrevok/go-iam:latest
